#!/bin/bash

#PBS -N minmiSimtest
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -l walltime=11:59:59
#PBS -j oe
#PBS -M David.Warton@unsw.edu.au
#PBS -m ae
#PBS -J 0-3

module add nlopt/2.7.0
module add gcc/12.2.0
module add gsl/2.7.1
module add r/4.3.0

cd fossils

Rscript -e "whichSims = as.numeric(Sys.getenv('PBS_ARRAY_INDEX'))*50+(1:2); source('doSims.R'); do.sim(whichSims,nSamp=c(12,24),date='20230714')"
